name: airflow-demon-summoning
version: 1.0.0
config-version: 2

profile: airflow-demon-summoning

target-path: target
clean-targets: [target, db_packages]

models:
  airflow-demon-summoning:
      core:
        materialized: table

      staging:
        materialized: ephemeral
