name: airflow_demon_summoning
version: 1.0.0
config-version: 2

profile: airflow_demon_summoning

target-path: target
clean-targets: [target, db_packages]

models:
  airflow_demon_summoning:
      core:
        materialized: table

      staging:
        materialized: ephemeral
