airflow_demon_summoning:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: "{{ env_var('WAREHOUSE_DB_PASSWORD') }}"
      port: 5432
      schema: core
      user: postgres
      type: postgres
  target: dev
