carepay_engelanna:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('WAREHOUSE_DB_PASSWORD') }}"
      dbname: postgres
      schema: core  # dbt will build objects here

