version: "3"
services:
  airflow_scheduler:
    command: bash -c "airflow db init && airflow scheduler"
    depends_on:
      - airflow_metadata_db
      - transactional_db
      - warehouse
    environment:
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://airflow:${AIRFLOW_METADATA_DB_PASSWORD}@0.0.0.0:5433/airflow
      - AIRFLOW_CONN_SOURCE_DB=mysql://root:${TRANSACTIONAL_DB_PASSWORD}@0.0.0.0:3306/carepay
      - AIRFLOW_CONN_TARGET_WAREHOUSE=postgresql://postgres:${WAREHOUSE_DB_PASSWORD}@0.0.0.0:5432/postgres
    image: apache/airflow:2.6.1
    network_mode: host
    volumes:
      - ./dags:/opt/airflow/dags

  # airflow_webserver:
  #   command: bash -c "airflow db init &&
  #                     airflow users create --role Admin --username admin --password ${AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD} --email admin@example.com --firstname _ --lastname _ &&
  #                     airflow webserver"
  #   depends_on:
  #     - airflow_metadata_db
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://airflow:${AIRFLOW_METADATA_DB_PASSWORD}@0.0.0.0:5433/airflow
  #     - AIRFLOW__WEBSERVER__AUTHENTICATE=True
  #     - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD
  #   image: apache/airflow:2.6.1
  #   network_mode: host

  airflow_metadata_db:
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=${AIRFLOW_METADATA_DB_PASSWORD}
      - POSTGRES_DB=airflow
    image: postgres:15
    ports:
      - "5433:5432"

  dbt:
    entrypoint: sh -c "dbt deps && /usr/bin/tail -f /dev/null"
    environment:
      - WAREHOUSE_DB_PASSWORD
      - DBT_PROFILES_DIR=/usr/app/dbt
    image: ghcr.io/dbt-labs/dbt-postgres:1.5.1
    network_mode: host
    volumes:
      - ./dbt:/usr/app/dbt

  transactional_db:
    environment:
      - MYSQL_ROOT_PASSWORD=${TRANSACTIONAL_DB_PASSWORD}
      - MYSQL_DATABASE=carepay
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/data
      - ./scripts/mysql:/docker-entrypoint-initdb.d

  warehouse:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${WAREHOUSE_DB_PASSWORD}
      - POSTGRES_DB=postgres
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
