version: "3"
services:
  warehouse:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${WAREHOUSE_DB_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  airflow-webserver:
    image: apache/airflow:2.6.1
    command: bash -c "airflow db init &&
                      airflow users create --username admin --firstname _ --lastname _ --email admin@example.com --role Admin --password ${AIRFLOW_WWW_PASSWORD} &&
                      airflow webserver"
                      
    environment: &airflow_common_env
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////home/airflow/airflow.db
      - AIRFLOW__CONN__SOURCE_DB=mysql://root:${TRANSACTIONAL_DB_PASSWORD}@localhost/carepay
      - AIRFLOW__CONN__TARGET_WAREHOUSE=postgres://postgres:${WAREHOUSE_DB_PASSWORD}@localhost:5432/staging
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
    volumes:
      - ./dags:/home/airflow/dags
    ports:
      - "8080:8080"
    depends_on:
      - warehouse

  airflow-scheduler:
    image: apache/airflow:2.6.1
    command: bash -c "airflow db init && airflow scheduler"
    environment: *airflow_common_env
    depends_on:
      - airflow-webserver

