CREATE TABLE INVOICE_ITEM (
    ID INT PRIMARY KEY,
    STATUS VARCHAR(25),
    DATE_CREATED DATETIME,
    INVOICE_ID INT,
    PRODUCT_ID INT,
    CURRENCY VARCHAR(4),
    AMOUNT DECIMAL(19,4)
);

CREATE TABLE INVOICE (
    ID INT PRIMARY KEY,
    STATUS VARCHAR(25),
    DATE_CREATED DATETIME,
    TREATMENT_ID INT
);

CREATE TABLE CLAIM (
    ID INT PRIMARY KEY,
    STATUS VARCHAR(25),
    TYPE VARCHAR(25),
    DATE_CREATED DATETIME,
    DATE_MODIFIED DATETIME,
    TREATMENT_ID INT,
    PROGRAM_ID INT,
    AMOUNT DECIMAL(19,4),
    CURRENCY VARCHAR(4)
);

CREATE TABLE TREATMENT (
    ID INT PRIMARY KEY,
    STATUS VARCHAR(25),
    DATE_CREATED DATETIME,
    DATE_MODIFIED DATETIME,
    DATE_SUBMITTED DATETIME, 
    DATE_TREATMENT DATETIME,
    PROVIDER_ID INT,
    PROGRAM_ID INT
);

LOAD DATA LOCAL INFILE  '/var/lib/data/invoice_items.csv' into table INVOICE_ITEM
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n' 
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE  '/var/lib/data/invoices.csv' into table INVOICE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n' 
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE  '/var/lib/data/claims.csv' into table CLAIM
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n' 
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE  '/var/lib/data/treatments.csv' into table TREATMENT
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n' 
IGNORE 1 LINES;
