CREATE TABLE staging.invoice_item (
    ID INT PRIMARY KEY,
    STATUS VARCHAR(25),
    DATE_CREATED TIMESTAMP,
    INVOICE_ID INT,
    PRODUCT_ID INT,
    CURRENCY VARCHAR(4),
    AMOUNT DECIMAL(19,4)
);

CREATE TABLE staging.invoice (
    ID INT PRIMARY KEY,
    STATUS VARCHAR(25),
    DATE_CREATED TIMESTAMP,
    TREATMENT_ID INT
);

CREATE TABLE staging.claim (
    ID INT PRIMARY KEY,
    STATUS VARCHAR(25),
    TYPE VARCHAR(25),
    DATE_CREATED TIMESTAMP,
    DATE_MODIFIED TIMESTAMP,
    TREATMENT_ID INT,
    PROGRAM_ID INT,
    AMOUNT DECIMAL(19,4),
    CURRENCY VARCHAR(4)
);

CREATE TABLE staging.treatment (
    ID INT PRIMARY KEY,
    STATUS VARCHAR(25),
    TYPE VARCHAR(25),
    DATE_CREATED TIMESTAMP,
    DATE_MODIFIED TIMESTAMP,
    DATE_SUBMITTED TIMESTAMP, 
    DATE_TREATMENT TIMESTAMP,
    PROVIDER_ID INT,
    PROGRAM_ID INT
);
